// Loads db/seed.sql, generated by generate-seed.ts, into the database
// pointed at by DATABASE_URL. Assumes migrations have already run.
import "./db-env.ts";
import { readFileSync } from "node:fs";
import { resolve } from "node:path";
import { Pool } from "pg";

async function main() {
  const connectionString = process.env.DATABASE_URL;
  if (!connectionString) {
    throw new Error("DATABASE_URL is not set. Copy .env.example to .env.local.");
  }
  const pool = new Pool({ connectionString });

  const { rows } = await pool.query<{ count: string }>("SELECT count(*)::text FROM tracks");
  if (Number(rows[0]!.count) > 0) {
    console.log(`tracks table already has ${rows[0]!.count} rows, skipping seed (run db:reset to start over)`);
    await pool.end();
    return;
  }

  const sql = readFileSync(resolve(import.meta.dirname, "..", "db", "seed.sql"), "utf8");
  await pool.query(sql);
  console.log("seed data loaded");
  await pool.end();
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
